// Sala 10: Remanso da Tartaruga. Água funda que ninguém pula. A tartaruga-menor nada
// de margem a margem e leva quem subir no casco; a segunda está em terra: empurre-a
// para o canal e ela vira balsa. (Se existe uma pequena, a grande também já foi pequena.)
export default {
  id: 'sala10',
  nome: 'Remanso da Tartaruga',
  subtitulo: 'o que carrega também já foi carregado',
  bioma: 'seiva',
  chao: [
    'tttttttttttttttttttttt',
    'trrrrrrrrroooooorrrrrt',
    'trrrrrrrrroooooorrrrrt',
    'tyyrrrrrrroooooorrrrrt',
    'trrrrrrrrroooooorrrrrt',
    'toooooooooooooooooooot',
    'toooooooooooooooooooot',
    'toooooooooooooooooooot',
    'toooooooooooooooooooot',
    'toooooooooooooooooooot',
    'toooooooooooooooooooot',
    'twwrrrrrrrrrrrrrrrrrrt',
    'twwwrrrrrrrrrrrrrrrwwt',
    'trrrrrrrrrrrrrrrrrwwwt',
    'trrrrrrrrrrrrrrrrrrrrt',
    'tttttttttttttttttttttt',
  ],
  coisas: [
    '                      ',
    '                  I   ',
    '         U        X   ',
    '  M                   ',
    '                      ',
    '                      ',
    '                      ',
    '                      ',
    '                      ',
    '                      ',
    '     U                ',
    '                      ',
    '                      ',
    '                    H ',
    '    P                 ',
    '                      ',
  ],
  deco: [
    ' v   v    v  v   v  v ',
    '    f              j  ',
    '  j                   ',
    '                    y ',
    '   y    i         m   ',
    '        x       x     ',
    '   x         x        ',
    '            x     x   ',
    '  x    x              ',
    '               x      ',
    '         x  x         ',
    ' x                 f  ',
    '           i       x  ',
    '   f   j            x ',
    '              m   y   ',
    '                      ',
  ],
  dicas: [
    { texto: 'Água funda: ninguém pula. Espere a tartaruga-menor na margem', atraso: 1.5 },
    { texto: 'Suba no casco quando ela parar na margem', em: [5, 11], raio: 2 },
    { texto: 'Tartaruga-menor. Se existe uma pequena… a grande também já foi pequena', em: [8, 2], raio: 2.2 },
    { texto: 'Empurre-a para o canal (encoste e ande contra ela) e espere ela voltar', em: [8, 2], raio: 1.2 },
  ],
};
