// Sala 9 (Ato II): Orla da Mata. Entrada da floresta do veio Seiva. A fauna daqui não
// ataca primeiro: o javali só investe em quem entra no território (anel no chão), o
// sapo só explode assustado, a planta só morde quem passa colado nela (banana distrai).
export default {
  id: 'sala09',
  nome: 'Orla da Mata',
  subtitulo: 'Ato II — Raiz da Matriarca',
  bioma: 'seiva',
  chao: [
    'tttttttttttttttttttttt',
    'ttttttttttttrttttttttt',
    'ttttyyyyytttrrtttttttt',
    'tttyyyyyytrrrrrtrrrrtt',
    'ttrrrrrrrrrrrrrrrrrrrt',
    'trrrrrrrrrrrrrrrrrrrrt',
    'trrrrr,,,,,rrrrrrrrrrt',
    'trrrr,,,,,,,rrrrrrrrrt',
    'trrrr,,,,,,,rrrrrrrrrt',
    'trrrr,,,,,,,rrrruurrrt',
    'trrrrr,,,,,rrrrrrrrrrt',
    'twwwrrrrrrrrrrrrrrrrrt',
    'twwwwrrrrrrrrrrrrrrrrt',
    'twwwwwrrrrrrrrrrrrrrtt',
    'ttwwwrrrrrrrrrrrrttttt',
    'tttttttttttttttttttttt',
  ],
  coisas: [
    '                      ',
    '            X         ',
    '             F        ',
    '                      ',
    '     I            I   ',
    '                      ',
    '                B     ',
    '                      ',
    '        J             ',
    '                      ',
    '                      ',
    '                      ',
    '  H                   ',
    '    H    P            ',
    '                      ',
    '                      ',
  ],
  deco: [
    ' v  v   v   v v   v   ',
    '           v  v       ',
    '    j        y   v    ',
    '  j        i     j m  ',
    '   y              f   ',
    ' f              y     ',
    '   i                  ',
    '             j        ',
    '                   y  ',
    '  y                   ',
    '             i        ',
    '  x                 j ',
    ' x   f         y      ',
    '   x          m     v ',
    '  x             f     ',
    '                      ',
  ],
  dicas: [
    { texto: 'A mata da Seiva: os bichos daqui não atacam primeiro', atraso: 1.5 },
    { texto: 'Sapo-bombástico: se assustar, incha e explode — deixe-o no brejo', em: [4, 12], raio: 3.2 },
    { texto: 'O anel no chão é o território do javali: contorne pela borda', em: [9, 11], raio: 3 },
    { texto: 'Planta-carnívora morde quem passa colado. Chico (2): banana (K) distrai', em: [13, 5], raio: 2.6 },
  ],
};
