// Sala 8: a Comporta dos Três. Chico sobe a muralha, Orlando plana até o pilar no meio
// do abismo e puxa a alavanca lá de cima, Hugo quebra o selo da comporta (e o do
// atalho de volta, que o drone construtor fecha de novo). Sem beco sem saída: quem planar direto para o
// outro lado sem puxar a alavanca volta pelo selo e tenta outra vez.
export default {
  id: 'sala08',
  nome: 'Comporta dos Três',
  subtitulo: 'um sobe, um voa, um quebra',
  reliquia: 'sismico',   // 'Y': Coração Sísmico, no alto da muralha (Chico)
  chao: [
    '######################',
    '#4444~~~~~~~~~...#...#',
    '#4444~~~~~~~~~...#+++#',
    '#4444~~~~k~~~~+++.+++#',
    '#4444~~~~~~~~~...#+++#',
    '#4444~~~~~~~~~...#####',
    '#4444~~~~~~~~~...#####',
    '#4444#########.#######',
    '#,,.............######',
    '#..........%%...######',
    '#...............######',
    '#..c.......k....######',
    '#...............######',
    '######################',
  ],
  coisas: [
    '                      ',
    ' Y                    ',
    '                   X  ',
    '         L      SD    ',
    '                   M  ',
    '               G      ',
    '                      ',
    '              S       ',
    '                      ',
    '  B         K         ',
    '        G             ',
    '  P                   ',
    '                      ',
    '                      ',
  ],
  deco: [
    ' v  v    v    v    v  ',
    'v                 b b ',
    '                      ',
    '              e       ',
    '                      ',
    '                f     ',
    '                      ',
    '     vvvvvvvvv v      ',
    'vgg                   ',
    '           q          ',
    'v                     ',
    '                      ',
    '     e         e      ',
    '                      ',
  ],
  dicas: [
    { texto: 'A comporta pede os três', atraso: 1.5 },
    { texto: 'Chico sobe a muralha', em: [3, 8], raio: 2 },
    { texto: 'A alavanca está no pilar do abismo: Orlando plana até ele (ou agarra de passagem)', em: [4, 3], raio: 2 },
    { texto: 'Hugo abre o atalho de volta — o drone vai lacrar de novo', em: [14, 8], raio: 2.5 },
    { texto: 'Selo na comporta: Hugo (1), Pulverizar', em: [15, 3], raio: 1.8 },
  ],
};
