// Sala 4: selos Quanta; só o Pulverizar do Hugo quebra.
export default {
  id: 'sala04',
  nome: 'Câmara dos Selos',
  subtitulo: 'lacres de quem veio depois',
  chao: [
    '##################',
    '#c....c#.........#',
    '#.++++.#.........#',
    '#.+..+.#...==....#',
    '#.++++.#..====...#',
    '#......#...=.....#',
    '###.#######=######',
    '#c.........=....c#',
    '#..11......22....#',
    '#..11......22....#',
    '#.......k........#',
    '#,,.............,#',
    '######=###########',
    '#####.=.##########',
    '##################',
  ],
  coisas: [
    '                  ',
    '                  ',
    '    P       X     ',
    '                  ',
    '                  ',
    '                  ',
    '   S       S      ',
    '                  ',
    '           T      ',
    '     G            ',
    '             G    ',
    '                  ',
    '      S           ',
    '      M           ',
    '                  ',
  ],
  deco: [
    '   v   v v  v  v  ',
    'v              a  ',
    '                  ',
    '                  ',
    '        f         ',
    'v                 ',
    '        v         ',
    'v                 ',
    '                  ',
    '               e  ',
    '       e          ',
    ' g              g ',
    '                  ',
    '     q q          ',
    '                  ',
  ],
  dicas: [
    { texto: 'Hugo (1): K Pulverizar quebra selos Quanta', em: [3, 5], raio: 2.5 },
    { texto: 'Hugo: segure L para a guarda — na hora certa, apara o tiro', em: [8, 8], raio: 3 },
    { texto: 'Um selo guarda uma memória', em: [6, 11], raio: 2 },
    { texto: 'O circuito leva ao último selo', em: [11, 8], raio: 2 },
  ],
};
