// Sala 3: Orlando puxa a alavanca (abre a porta) e plana sobre o abismo.
export default {
  id: 'sala03',
  nome: 'Eclusa dos Ventos',
  subtitulo: 'a máquina ainda obedece a quem puxa',
  chao: [
    '####################',
    '#44444~~~~.......###',
    '#44444~~~~.......###',
    '#44444~~~~...,,..###',
    '#33333~~~~.......###',
    '#22222~~~~~~~~~~~###',
    '#11111~~~~~~~~~~~###',
    '#.........~~~~~~~###',
    '#.........~~~~~~~###',
    '#####.##############',
    '#..................#',
    '#..,,..............#',
    '#..,,..............#',
    '#.............22...#',
    '#.............22...#',
    '####################',
  ],
  coisas: [
    '                    ',
    '                    ',
    '              M     ',
    '              X     ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '     D              ',
    '                    ',
    '                    ',
    '          G         ',
    '  P                 ',
    '                 L  ',
    '                    ',
  ],
  dicas: [
    { texto: 'Orlando (3): K agarra e puxa alavancas', em: [17, 14], raio: 3 },
    { texto: 'A alavanca abriu a porta', em: [5, 10], raio: 1.5 },
    { texto: 'Orlando: segure Espaço caindo para planar', em: [4, 2], raio: 2.5 },
  ],
};
