// Sala 6: altar-circuito Quanta. Hugo quebra o selo, Orlando plana e puxa a
// alavanca, Chico sobe ao altar. Os três macacos, um de cada vez.
export default {
  id: 'sala06',
  nome: 'Altar do Circuito',
  subtitulo: 'a máquina que ainda funciona',
  chao: [
    '######################',
    '#4444~~~~=======#....#',
    '#4444~~~~==....=#....#',
    '#4444~~~~==.%%.=#....#',
    '#4444~~~~==....=#.==.#',
    '#4444~~~~==....=.....#',
    '#4444~~~~==....=#....#',
    '#k444~~~~==.%%.=#.==.#',
    '#3333~~~~==....=#....#',
    '#2222~~~~==....=#....#',
    '#1111~~~~=======#....#',
    '###.#############....#',
    '#c.............c#....#',
    '#..====.........#++++#',
    '#..====.........#4444#',
    '#...............#4444#',
    '#...............#4444#',
    '#.......k.......#4444#',
    '######################',
  ],
  coisas: [
    '                      ',
    '                      ',
    '             A        ',
    '            M     Q   ',
    '                      ',
    '                D     ',
    '            Q         ',
    '                      ',
    '             L    A   ',
    '                      ',
    '                      ',
    '   S                  ',
    '                      ',
    '                      ',
    '             Q        ',
    '                      ',
    '  P      K    A   X   ',
    '                      ',
    '                      ',
  ],
  deco: [
    '  v   v   v  v  v  v  ',
    'v   g               v ',
    '   f                  ',
    '                      ',
    '                      ',
    '             a        ',
    '                      ',
    '                      ',
    'v                     ',
    '                      ',
    '                      ',
    '  v             v     ',
    'v                     ',
    '      q            e  ',
    '                  b   ',
    'v                     ',
    '                  e   ',
    '    e              b  ',
    '                      ',
  ],
  dicas: [
    { texto: 'Hugo quebra o selo — o drone construtor tenta reerguê-lo', em: [3, 12], raio: 2 },
    { texto: 'Do alto, Orlando plana até o circuito', em: [3, 3], raio: 2.5 },
    { texto: 'Acólitos somem e reaparecem · Orlando (L) desliga Torres de perto', em: [11, 4], raio: 3 },
    { texto: 'O altar é alto: pulo duplo do Chico', em: [18, 11], raio: 2.5 },
  ],
};
