// Sala 6: altar-circuito Quanta. Hugo quebra o selo, Orlando plana e puxa a
// alavanca, Chico sobe ao altar.
export default {
  id: 'sala06',
  nome: 'Altar do Circuito',
  subtitulo: 'a máquina que ainda funciona',
  chao: [
    '######################',
    '#4444~~~~=======#....#',
    '#4444~~~~==....=#....#',
    '#4444~~~~==.,,.=#....#',
    '#4444~~~~==....=#.==.#',
    '#4444~~~~==....=.....#',
    '#4444~~~~==....=#....#',
    '#4444~~~~==.,,.=#.==.#',
    '#3333~~~~==....=#....#',
    '#2222~~~~==....=#....#',
    '#1111~~~~=======#....#',
    '###.#############....#',
    '#...............#....#',
    '#..====.........#4444#',
    '#..====.........#4444#',
    '#...............#4444#',
    '#...............#4444#',
    '#...............#4444#',
    '######################',
  ],
  coisas: [
    '                      ',
    '                      ',
    '             A        ',
    '                  Q   ',
    '                      ',
    '                D     ',
    '            Q         ',
    '                      ',
    '             L    A   ',
    '                      ',
    '                      ',
    '   S                  ',
    '                      ',
    '     Q                ',
    '                      ',
    '          A           ',
    '  P      K        X   ',
    '                      ',
    '                      ',
  ],
  dicas: [
    { texto: 'Hugo quebra o selo — o drone construtor tenta reerguê-lo', em: [3, 12], raio: 2 },
    { texto: 'Do alto, Orlando plana até o circuito', em: [3, 3], raio: 2.5 },
    { texto: 'Acólitos somem e reaparecem — fique atento', em: [13, 3], raio: 3 },
    { texto: 'O altar é alto: pulo duplo do Chico', em: [18, 11], raio: 2.5 },
  ],
};
