// Sala 12: Clareira da Matriarca. Ela não luta: reage. As raízes vivas (brilham) são
// dela; quem pisa nelas, ou fere o que vive perto dela, leva pisão sísmico (pule a
// onda), chicote de raízes em linha (saia da faixa vermelha) e esporos (saia da nuvem).
// Dá para atravessar a clareira sem encostar em nada que ela protege, pegar a
// Semente Primordial aos pés dela e sair. Ou brigar, se ela for provocada.
export default {
  id: 'sala12',
  nome: 'Clareira da Matriarca',
  subtitulo: 'a floresta luta · a Matriarca protege · e tudo faz parte',
  bioma: 'seiva',
  reliquia: 'semente',
  chao: [
    'tttttttttttttttttttttttttt',
    'tttttttttttttttttttrrrrrrt',
    'tttttttttrrrrrrrtttrrrrrrt',
    'tyyrrrrrrrrrrrrrrrrrrrzzrt',
    'trrrrrrrrrrrrrrrrrrrrzzrrt',
    'trrrrrrrrrzrrrzrrrrrzzrrrt',
    'trrrrrrrrrzrrrzrrrrzzrrrrt',
    'trrrrrrrrrzrrrzrrrrrrrrrrt',
    'trrrrrrrrrzrrrzrrrrrrrrrrt',
    'trrrrrrrrrrrrrrrrrrrrrrrrt',
    'tzzzrrzzzzzzzzzzzzzrrzzzzt',
    'trrrrrrrrrrrrrrrrrrrrrrrrt',
    'trrrrrrrrrrrrrrrrrrrrrrrrt',
    'trrrrrrrrrrrrrrrrrrrrrrrrt',
    'tzzzzzzzzzzzrrzzzzzzzzzzzt',
    'trrrrrrrrrrrrrrrrrrrrrrrrt',
    'trrrrrrrrrrrrrrrrrrrrrrrrt',
    'trrrwwwrrrrrrrrrrrrrwwwrrt',
    'ttrrwwrrrrrrrrrrrrrrrwwrtt',
    'tttrrrrrrrrrrrrrrrrrrrrttt',
    'tttttttttttttttttttttttttt',
  ],
  coisas: [
    '                          ',
    '                        X ',
    '                          ',
    '                          ',
    '            Z             ',
    '                          ',
    '                          ',
    '            Y             ',
    '                          ',
    '                          ',
    '                          ',
    '  I                    I  ',
    '                          ',
    '                          ',
    '                          ',
    '                          ',
    '                          ',
    '                          ',
    '                          ',
    '            P             ',
    '                          ',
  ],
  deco: [
    ' v  v  v  v   v  v  v  v  ',
    '           v    v   j     ',
    '         i            f   ',
    '   j                      ',
    ' f     m           i      ',
    '                         m',
    '  i                       ',
    '                      j   ',
    '    y                 y   ',
    '                          ',
    '                          ',
    '                    f     ',
    '       y                  ',
    '                y         ',
    '                          ',
    '     i                    ',
    '                   i      ',
    '    x                x    ',
    '     x  j        j    x   ',
    '   f       m              ',
    '                          ',
  ],
  dicas: [
    { texto: 'A Matriarca não ataca primeiro. As raízes que brilham são dela', atraso: 1.5 },
    { texto: 'Não pise nas raízes vivas: ache as passagens', em: [12, 16], raio: 3 },
    { texto: 'Provocada: pule o pisão · saia da faixa vermelha · fuja dos esporos', em: [12, 11], raio: 3 },
    { texto: 'A Semente Primordial, aos pés dela', em: [12, 9], raio: 2.2 },
  ],
};
