// Sala 2: só o Chico sobe a muralha (pulo duplo). Cachos recarregam as bananas.
export default {
  id: 'sala02',
  nome: 'Galeria dos Cachos',
  subtitulo: 'o que é alto demais para um, é degrau para outro',
  chao: [
    '##################',
    '#,,.....#444~~444#',
    '#,,.....#444~~444#',
    '#.......#444~~444#',
    '#.......4444~~444#',
    '#.......4444~~444#',
    '#..44...4444~~444#',
    '#..44...4444~~333#',
    '#.......4444~~222#',
    '#.......#444~~111#',
    '#.......#444~~...#',
    '#.......#444~~.,.#',
    '##################',
  ],
  coisas: [
    '                  ',
    '                  ',
    '     B            ',
    '                  ',
    '                  ',
    '          M       ',
    '   T              ',
    '                  ',
    '                  ',
    '                  ',
    '  P               ',
    '               X  ',
    '                  ',
  ],
  dicas: [
    { texto: 'Chico (2): Espaço duas vezes para o pulo duplo', em: [7, 6], raio: 2.5 },
    { texto: 'Chico: K taca banana · cachos recarregam', em: [5, 2], raio: 2.5 },
    { texto: 'A Sentinela atira de longe', em: [3, 6], raio: 4 },
  ],
};
