// Sala 1: o santuário de embarque. Ensina andar, golpear, pular degrau e o Surto.
// A saída fica atrás de um degrau alto: o primeiro pulo é obrigatório.
export default {
  id: 'sala01',
  nome: 'Doca do Santuário',
  subtitulo: 'a ruína lembra quem embarcou',
  chao: [
    '##############',
    '#c..........c#',
    '#..,,....22..#',
    '#..,,....22..#',
    '#........22..#',
    '#k...........#',
    '#...====.....#',
    '#...====..~~.#',
    '#.........~~.#',
    '#....++++....#',
    '######22######',
    '     #++#     ',
    '     #++#     ',
  ],
  coisas: [
    '              ',
    '              ',
    '    G     M   ',
    '              ',
    '              ',
    '              ',
    '              ',
    '              ',
    '  P           ',
    '              ',
    '              ',
    '              ',
    '      X       ',
  ],
  deco: [
    ' vv   v   vv  ',
    'v            v',
    '   gg       f ',
    'f  gg         ',
    '             e',
    ' e           f',
    '       q      ',
    '              ',
    'f             ',
    '    b    b    ',
    '              ',
    '              ',
    '              ',
  ],
  // dicas: `em` = tile [i, j] que dispara ao chegar perto (raio em tiles); sem `em`, aparece ao entrar
  dicas: [
    { texto: 'WASD anda · Q/E gira a câmera' },
    { texto: 'J golpeia — o Guardião avisa antes de bater (!)', em: [4, 2], raio: 5 },
    { texto: 'Espaço pula — degraus altos pedem pulo', em: [6, 9], raio: 2.5 },
    { texto: 'Pule no bloco para pegar o fragmento', em: [9, 4], raio: 1.6 },
    { texto: 'Fragmentos de memória enchem o Surto (F)', em: [10, 2], raio: 1.8 },
    { texto: '1 Hugo · 2 Chico · 3 Orlando — cada um passa onde o outro não passa', em: [6, 10], raio: 1.5 },
  ],
};
