// Sala 7: arena do Andador Quanta (chefe). O portão do embarque só abre quando ele cai.
// Os pilares guardam memórias (só o Chico alcança); o Hugo quebra os selos onde ele se esconde.
export default {
  id: 'sala07',
  nome: 'Arena do Andador',
  subtitulo: 'o guardião do embarque ainda anda',
  chao: [
    '########################',
    '##########++++##########',
    '##########++++##########',
    '###########+############',
    '##....................##',
    '#......................#',
    '#..44..............44..#',
    '#..44....======....44..#',
    '#.......=......=.......#',
    '#k......=......=......k#',
    '#.......=......=.......#',
    '#.......=......=.......#',
    '#..44....======....44..#',
    '#..44..............44..#',
    '#......................#',
    '#,.....................#',
    '##,,................,,##',
    '####...+...22...+...####',
    '####...++++++++++...####',
    '########################',
  ],
  coisas: [
    '                        ',
    '                        ',
    '           X            ',
    '           D            ',
    '                        ',
    '                        ',
    '   M                    ',
    '                        ',
    '                        ',
    '      S          S      ',
    '           W            ',
    '                        ',
    '                        ',
    '                    M   ',
    '         S    S         ',
    '                        ',
    '                        ',
    '                        ',
    '           P            ',
    '                        ',
  ],
  deco: [
    '    v  v  v    v  v  v  ',
    '          b  b          ',
    '                        ',
    '  v                  v  ',
    'v                       ',
    '  e                  q  ',
    '                        ',
    '                        ',
    '                        ',
    '                        ',
    '                        ',
    '                        ',
    '                        ',
    '                        ',
    '       e                ',
    'v                  h    ',
    '                        ',
    '    q            e      ',
    '                        ',
    '                        ',
  ],
  dicas: [
    { texto: 'O Andador Quanta desperta — derrube-o e o portão se abre', em: [11, 15], raio: 3 },
    { texto: 'Círculo vermelho: saia dele · anel azul no chão: pule', em: [11, 12], raio: 4 },
    { texto: 'Rajada: os pilares seguram os tiros — ou erga a guarda do Hugo (L)', em: [11, 12], raio: 6 },
    { texto: 'Ele se esconde atrás dos selos: Hugo, quebre-os', em: [9, 13], raio: 2.5 },
    { texto: 'O drone reergue os selos — derrube-o', em: [11, 9], raio: 3 },
    { texto: 'Pilares: só o Chico alcança as memórias (Surto no F)', em: [4, 8], raio: 2.5 },
  ],
};
