// Sala 11: Berçário das Tecelãs. Dois bandos de ovos fecham o corredor: pisar em um
// acorda as aranhas. O Chico passa por cima com o pulo duplo, o Orlando planando; o Hugo
// só passa brigando. Lá em cima, a alavanca da porta está numa ilha: Agarrão do Orlando.
export default {
  id: 'sala11',
  nome: 'Berçário das Tecelãs',
  subtitulo: 'quem pisa nos ovos acorda a mãe',
  bioma: 'seiva',
  chao: [
    'tttttttttttttttttttt',
    'trrrtttrrrrrtoooooot',
    'trrrrrrrrrrrroorooot',
    'trrrtrrrrrrrroooooot',
    'tttttrrrrrrrroooooot',
    'ttttttrrrrrrrttttttt',
    'ttttttttrrrttttttttt',
    'ttttttttrrrttttttttt',
    'ttttttttrrrttttttttt',
    'ttttttttrrrttttttttt',
    'ttttttttrrrttttttttt',
    'ttttttttrrrttttttttt',
    'tttrrrrrrrrrrrrrrttt',
    'trrrrrrrrrrrrrrrrrrt',
    'trrrrrrrrrrrrrrrrrrt',
    'trrrrrrrrrrrrrrrrrrt',
    'trrrrrrrrrrrrrrrrrrt',
    'tttttttttttttttttttt',
  ],
  coisas: [
    '                    ',
    '                    ',
    '  X D          L    ',
    '      F             ',
    '          B         ',
    '                    ',
    '                    ',
    '        E           ',
    '        NNN         ',
    '        NNN         ',
    '          E         ',
    '                    ',
    '                    ',
    '    I          H    ',
    '                    ',
    '         P          ',
    '                    ',
    '                    ',
  ],
  deco: [
    '  v  v   v  v   v v ',
    '                    ',
    '                x   ',
    '        y     x   x ',
    '     j        x     ',
    '       m            ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '   i            j   ',
    ' f    y      m    f ',
    '  j            y    ',
    '     i     f        ',
    ' y              j   ',
    '                    ',
  ],
  dicas: [
    { texto: 'Ninhos de aranha-gigante: pisar nos ovos acorda as mães', atraso: 1.5 },
    { texto: 'Chico (2): pulo duplo por cima dos ovos · Orlando (3): pule e plane', em: [9, 11], raio: 2 },
    { texto: 'Planta no caminho: uma banana (Chico, K) a distrai', em: [8, 3], raio: 2.5 },
    { texto: 'A alavanca está na ilha: Orlando (3), Agarrão (K) da margem', em: [12, 2], raio: 2 },
  ],
};
