// Sala 4: selos Quanta; só o Pulverizar do Hugo quebra.
export default {
  id: 'sala04',
  nome: 'Câmara dos Selos',
  subtitulo: 'lacres de quem veio depois',
  chao: [
    '##################',
    '#......#.........#',
    '#......#.........#',
    '#......#...==....#',
    '#..,,..#..====...#',
    '#......#.........#',
    '###.#######.######',
    '#................#',
    '#..11......22....#',
    '#..11......22....#',
    '#................#',
    '#,,.............,#',
    '######.###########',
    '#####...##########',
    '##################',
  ],
  coisas: [
    '                  ',
    '                  ',
    '   P        X     ',
    '                  ',
    '                  ',
    '                  ',
    '   S       S      ',
    '                  ',
    '           T      ',
    '     G            ',
    '             G    ',
    '                  ',
    '      S           ',
    '      M           ',
    '                  ',
  ],
  dicas: [
    { texto: 'Hugo (1): K Pulverizar quebra selos', em: [3, 5], raio: 2.5 },
    { texto: 'Hugo: L ergue a guarda', em: [6, 8], raio: 3 },
    { texto: 'Um selo guarda uma memória', em: [6, 11], raio: 2 },
  ],
};
