// Sala 2: só o Chico sobe a muralha (pulo duplo). O pilar baixo é o treino;
// a Sentinela vigia o outro lado do vão. Cachos recarregam as bananas.
export default {
  id: 'sala02',
  nome: 'Galeria dos Cachos',
  subtitulo: 'o que é alto demais para um, é degrau para outro',
  chao: [
    '##################',
    '#,,.....#444~~444#',
    '#,,.....#444~~444#',
    '#c......#444~~444#',
    '#.......4444~~444#',
    '#.......4444~~444#',
    '#..44...4444~~444#',
    '#..44...4444~~333#',
    '#.......4444~~222#',
    '#c......#444~~111#',
    '#.......#444~~...#',
    '#.......#444~~.,.#',
    '##################',
  ],
  coisas: [
    '                  ',
    '                  ',
    '     B            ',
    '                  ',
    '                  ',
    '          M       ',
    '   M           T  ',
    '                  ',
    '                  ',
    '                  ',
    '  P               ',
    '               X  ',
    '                  ',
  ],
  deco: [
    '  vv  v  v  v   v ',
    'vgg      f     g  ',
    ' gg              v',
    '                  ',
    'v            g  f ',
    '        e         ',
    '     e            ',
    '   f              ',
    'v             q   ',
    '         f      v ',
    '     f            ',
    'v              g  ',
    '                  ',
  ],
  dicas: [
    { texto: 'A muralha é alta demais para o Hugo', em: [7, 7], raio: 2 },
    { texto: 'Chico (2): Espaço duas vezes para o pulo duplo — treine no pilar', em: [4, 8], raio: 2.2 },
    { texto: 'Chico: K taca banana e derruba · cachos recarregam', em: [5, 2], raio: 2.5 },
    { texto: 'A Sentinela atira de longe — uma banana a faz escorregar', em: [11, 4], raio: 2.5 },
  ],
};
