// Sala 5: combate misto da Legião Cinzenta — Guardiões, Sentinela, Drone Vigia e um Bruto.
// A alavanca fica no terraço da Sentinela; as caixas servem de cobertura (e de arma do Orlando).
export default {
  id: 'sala05',
  nome: 'Pátio da Legião',
  subtitulo: 'os cinzentos ainda guardam o que não entendem',
  chao: [
    '######################',
    '#.....#.....2222.#...#',
    '#.+++.#.....2222.#+++#',
    '#.....#.....1111.#+++#',
    '#.....#..............#',
    '#.................####',
    '#.....#..............#',
    '#c...c#..............#',
    '#######.....33.......#',
    '#....................#',
    '#..44................#',
    '#..44................#',
    '#######..............#',
    '#######..............#',
    '#######..222222......#',
    '#######..222222......#',
    '#######..............#',
    '######################',
  ],
  coisas: [
    '                      ',
    '            T L       ',
    '   P               X  ',
    '                      ',
    '         G       D    ',
    '                      ',
    '         C     C      ',
    '           V          ',
    '                      ',
    '                      ',
    '   M       G          ',
    '                      ',
    '                      ',
    '                   R  ',
    '                      ',
    '                      ',
    '                      ',
    '                      ',
  ],
  deco: [
    ' v   v    v    v   v  ',
    'v     v            b  ',
    '                      ',
    '      h               ',
    '                      ',
    '        e         v   ',
    'v                     ',
    '       h              ',
    '  v v v       e       ',
    'v                  h  ',
    '                      ',
    '     e                ',
    '  v v v   b           ',
    '       e              ',
    '                      ',
    '                 h    ',
    '        e      e      ',
    '                      ',
  ],
  dicas: [
    { texto: 'O drone vigia dá o alarme — derrube-o primeiro', em: [11, 7], raio: 5 },
    { texto: 'Caixas bloqueiam os tiros · Orlando (K) arremessa caixas nos inimigos', em: [9, 6], raio: 2.5 },
    { texto: 'O Bruto avança em linha — saia da frente e ele bate na parede', em: [19, 13], raio: 7 },
    { texto: 'A porta abre pela alavanca no terraço', em: [16, 4], raio: 2.5 },
  ],
};
