// Sala 3: Orlando puxa a alavanca (abre a porta) e plana sobre a eclusa.
// O vão tem 6 tiles: só o planeio atravessa.
export default {
  id: 'sala03',
  nome: 'Eclusa dos Ventos',
  subtitulo: 'a máquina ainda obedece a quem puxa',
  chao: [
    '####################',
    '#44444~~~~~~++++.###',
    '#44444~~~~~~+..+.###',
    '#44444~~~~~~+..+,###',
    '#33333~~~~~~++++.###',
    '#22222~~~~~~~~~~~###',
    '#11111~~~~~~~~~~~###',
    '#.....~~~~~~~~~~~###',
    '#k....~~~~~~~~~~~###',
    '#####.##############',
    '#.............=....#',
    '#..,,.........=....#',
    '#..,,....%%...=....#',
    '#........%%...22...#',
    '#c............22...#',
    '####################',
  ],
  coisas: [
    '                    ',
    '                M   ',
    '                    ',
    '              X     ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '     D              ',
    '                    ',
    '                    ',
    '           G        ',
    '  P                 ',
    '                 L  ',
    '                    ',
  ],
  deco: [
    '  v  v  v  v  vv    ',
    'v           b  b    ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    '                    ',
    'v                   ',
    '                    ',
    ' v   vv   v  v  v   ',
    'v                   ',
    '                    ',
    '         q          ',
    'f                   ',
    '    e          e  q ',
    '                    ',
  ],
  dicas: [
    { texto: 'Porta trancada — alguém tem que puxar uma alavanca', em: [5, 10], raio: 2 },
    { texto: 'Orlando (3): K agarra de longe e puxa alavancas', em: [17, 14], raio: 4 },
    { texto: 'A eclusa é larga demais para pular', em: [3, 4], raio: 2 },
    { texto: 'Orlando: segure Espaço caindo para planar', em: [5, 2], raio: 2 },
  ],
};
