// Sala 5: combate misto da Legião Cinzenta — Guardiões, Sentinelas e um Bruto.
export default {
  id: 'sala05',
  nome: 'Pátio da Legião',
  subtitulo: 'os cinzentos ainda guardam o que não entendem',
  chao: [
    '######################',
    '#.....#......2222#...#',
    '#.....#......2222#...#',
    '#.....#......1111#...#',
    '#.....#..............#',
    '#.................####',
    '#.....#..............#',
    '#.....#..............#',
    '#######.....33.......#',
    '#4444.......33.......#',
    '#4444................#',
    '#4444................#',
    '#######..............#',
    '#######..............#',
    '#######..222222......#',
    '#######..222222......#',
    '#######..............#',
    '######################',
  ],
  coisas: [
    '                      ',
    '               L      ',
    '   P          T    X  ',
    '                      ',
    '         G       D    ',
    '                      ',
    '         C       C    ',
    '                      ',
    '               V      ',
    '                      ',
    '  M        G          ',
    '                      ',
    '                      ',
    '                   R  ',
    '           T          ',
    '                      ',
    '                      ',
    '                      ',
  ],
  dicas: [
    { texto: 'O drone vigia dá o alarme — derrube-o primeiro', em: [12, 7], raio: 4 },
    { texto: 'Caixas bloqueiam os tiros das Sentinelas', em: [9, 6], raio: 2.5 },
    { texto: 'O Bruto avança em linha — saia da frente', em: [17, 12], raio: 4 },
    { texto: 'Orlando puxa a alavanca no terraço', em: [14, 3], raio: 2.5 },
  ],
};
